# Generated by Django 2.2.12 on 2021-03-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rising_Tide_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distancetocoast',
            options={'managed': True},
        ),
    ]
